import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const config = fs.readFileSync(path.join(root, 'js', 'supabase-config.js'), 'utf8');
const guard = fs.readFileSync(path.join(root, 'js', 'auth-guard.js'), 'utf8');
const fallback = fs.readFileSync(path.join(root, 'js', 'runtime-fallback.js'), 'utf8');
const home = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const callback = fs.readFileSync(path.join(root, 'auth-callback.html'), 'utf8');
assert.match(config, /window\.supabaseClient = null/);
assert.match(config, /try \{/);
assert.match(guard, /AUTH_TIMEOUT_MS/);
assert.match(guard, /Account service unavailable/);
assert.match(fallback, /could not finish loading/);
assert.match(home, /js\/runtime-fallback\.js/);
assert.match(home, /Guest homepage auth check skipped/);
assert.match(callback, /Authentication timed out/);
assert.match(callback, /Return to Login/);
console.log('BLANK_PAGE_REGRESSION_PASS public-fallback=present protected-timeout=present callback-recovery=present');
