import fs from 'node:fs';
import assert from 'node:assert/strict';

const read = (file) => fs.readFileSync(new URL(`../${file}`, import.meta.url), 'utf8');
const dashboard = read('dashboard.html');
const library = read('library.html');
const challenges = read('challenges.html');
const leaderboard = read('leaderboard.html');

assert.match(dashboard, /Nexal Pathway/);
assert.match(dashboard, /Continue learning/i);
assert.match(dashboard, /FREE PLAN/);
assert.match(dashboard, /id="course-grid"/);
assert.match(dashboard, /Your current-grade subjects/);
assert.match(dashboard, /caps-master-manifest\.json/);
assert.doesNotMatch(dashboard, /Current Rank/);
assert.doesNotMatch(dashboard, /Active Syllabus/);
assert.match(library, /caps-master-manifest\.json/);
assert.match(library, /Your current-grade units/i);
assert.match(library, /18<\/span> units in this programme/);
assert.match(library, /id="grade"/);
assert.match(library, /id="subject"/);
assert.match(library, /id="search"/);
assert.match(library, /study-hall\.html\?unit=/);
assert.match(challenges, /Verified CAPS Challenges/i);
assert.match(challenges, /Server-verified competition/i);
assert.match(challenges, /academy_create_challenge/);
assert.match(challenges, /academy_list_my_challenges/);
assert.doesNotMatch(challenges, /top 5%|\+2,500 XP|Calculus Gauntlet|Coming soon/i);
assert.doesNotMatch(leaderboard, /aiScholars|Global Standard/i);
console.log('premium-ui smoke: PASS');
